### ISSUE TITLE
[Doc] update maintainer doc 

### ISSUE THREAD

**Issue by seraphjiang** [opensearch-project/opensearch-dashboards-test-library#16]
update maintainer doc
https://github.com/opensearch-project/opensearch-dashboards-test-library/blob/main/MAINTAINERS.md

**Comment by seraphjiang** [comment]
nominate @tianleh  @Tengda-He  per 
https://github.com/opensearch-project/.github/blob/main/MAINTAINERS.md#becoming-a-maintainer

**Comment by tianleh** [comment]
> nominate @tianleh @Tengda-He per
> https://github.com/opensearch-project/.github/blob/main/MAINTAINERS.md#becoming-a-maintainer

Do you have an update list to nominate? @seraphjiang
