### ISSUE TITLE
Baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-dashboards-test-library#29]
Follow https://github.com/opensearch-project/.github/issues/125 to baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions.

Close this issue when:

1. [MAINTAINERS.md](MAINTAINERS.md) has the correct list of project maintainers.
2. [CODEOWNERS](CODEOWNERS) exists and has the correct list of aliases.
3. Repo permissions only contain individual aliases as collaborators with maintain rights, admin, and triage teams. 
4. All other teams are removed from repo permissions.

If this repo's permissions was already baselined, please confirm the above when closing this issue.

**Comment by CCongWang** [comment]
https://github.com/opensearch-project/opensearch-dashboards-test-library/blob/main/MAINTAINERS.md has correct list of maintainers

**Comment by seraphjiang** [comment]
@CCongWang has been granted to admin permission

**Comment by tianleh** [comment]
checking

**Comment by seraphjiang** [comment]
@dblock i'm not sure i'm following. 

the request is to baseline CodeOwner and Maintainer not Admin right?

> @seraphjiang That is incorrect. Only members of "admin" should be granted admin permissions. And the functional-test-admin group should be deleted.

**Comment by tianleh** [comment]
@dblock Is the admin part a must have to close the issue per @seraphjiang 's question above?

**Comment by bbarani** [comment]
@seraphjiang There should be no other team apart from opensearch-project/admin and triage team. Everyone else should be added as individual users.

**Comment by tianleh** [comment]
> @seraphjiang There should be no other team apart from opensearch-project/admin and triage team. Everyone else should be added as individual users (with appropriate access but cannot be admin).

@bbarani Step 7 in https://github.com/opensearch-project/.github/issues/125 says that you could help sync the repo permissions. Could you please help?

Also if I do not have admin permission, I may loose access to "Settings" tab. This means that we will need your (or other org admin) help to grant permissions for a new maintainer.

**Comment by tianleh** [comment]
Updated admins as well.

**Comment by dblock** [comment]
verified, thanks.
